exam_prep_two/exam_prep_two/profiles/urls.py
from django.urls import path

from exam_prep_two.profiles.views import create_profile, edit_profile, details_profile, delete_profile

urlpatterns = (
    path('create/', create_profile, name='create_profile'),
    path('edit/', edit_profile, name='edit_profile'),
    path('details/', details_profile, name='details_profile'),
    path('delete/', delete_profile, name='delete_profile'),
)

exam_prep_two/exam_prep_two/urls.py
"""
MAIN URLS
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('exam_prep_two.mainpage.urls')),
    path('fruit/', include('exam_prep_two.fruits.urls')),
    path('profile/', include('exam_prep_two.profiles.urls')),
]

exam_prep_two/exam_prep_two/fruits/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models

from exam_prep_two.profiles.models import Profile


def letters_only_validator(value):
    if not value.isalpha():
        raise ValidationError("Fruit name should contain only letters!")


class Fruits(models.Model):
    MAX_FRUIT_LENGTH = 30
    MIN_FRUIT_LENGTH = 2

    name = models.CharField(
        max_length=MAX_FRUIT_LENGTH,
        validators=(
            MinLengthValidator(MIN_FRUIT_LENGTH),
            letters_only_validator,
        ),
        unique=True,
        blank=False,
        null=False,
    )

    image_url = models.URLField(
        null=False,
        blank=False,
    )

    description = models.TextField(
        null=False,
        blank=False,
    )

    nutrition = models.TextField(
        null=True,
        blank=True,
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
    )

exam_prep_two/exam_prep_two/profiles/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models


def starts_with_letter_validator(value):
    if not value[0].isalpha():
        raise ValidationError("Your name must start with a letter!")


class Profile(models.Model):
    MAX_FIRST_NAME_LENGTH = 25
    MIN_FIRST_NAME_LENGTH = 2

    MAX_LAST_NAME_LENGTH = 35
    MIN_LAST_NAME_LENGTH = 1

    MAX_EMAIL_LENGTH = 40

    MAX_PASSWORD_LENGTH = 20
    MIN_PASSWORD_LENGTH = 8

    first_name = models.CharField(
        max_length=MAX_FIRST_NAME_LENGTH,
        validators=(
            MinLengthValidator(MIN_FIRST_NAME_LENGTH),
            starts_with_letter_validator,
        ),
        blank=False,
        null=False,
    )

    last_name = models.CharField(
        max_length=MAX_LAST_NAME_LENGTH,
        validators=(
            MinLengthValidator(MIN_LAST_NAME_LENGTH),
            starts_with_letter_validator,
        ),
        blank=False,
        null=False,
    )

    email = models.EmailField(
        max_length=MAX_EMAIL_LENGTH,
        unique=True,
        blank=False,
        null=False,
    )

    password = models.CharField(
        max_length=MAX_PASSWORD_LENGTH,
        validators=(MinLengthValidator(MIN_PASSWORD_LENGTH),),
        blank=False,
        null=False,
        help_text="*Password length requirements: 8 to 20 characters",
    )

    image_url = models.URLField(
        null=True,
        blank=True,
    )

    age = models.PositiveIntegerField(
        null=True,
        blank=True,
        default=18,
    )

exam_prep_two/exam_prep_two/profiles/forms.py
from django import forms

from exam_prep_two.profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['owner', 'age', 'image_url']

        labels = {
            'first_name': '',
            'last_name': '',
            'email': '',
            'password': '',
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }


class EditProfileForm(CreateProfileForm):
    class Meta:
        model = Profile
        exclude = ['owner', 'password', 'email']

        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'image_url': 'Image URL',
            'age': 'Age',
        }


class DeleteProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['password', 'image_url', 'first_name', 'last_name', 'email', 'age']

    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance

exam_prep_two/exam_prep_two/profiles/views.py
from django.shortcuts import render, redirect

from exam_prep_two.mainpage.views import get_profile
from exam_prep_two.profiles.forms import CreateProfileForm, EditProfileForm, DeleteProfileForm
from exam_prep_two.profiles.models import Profile


# Create your views here.

def create_profile(request):
    create_form = CreateProfileForm(request.POST or None)

    profile = get_profile()
    no_profile = False

    if profile is None:
        no_profile = True

    if request.method == 'POST':
        if create_form.is_valid():
            create_form.save()
            return redirect('dashboard')

    context = {
        'create_form': create_form,
        'no_profile': no_profile,
    }

    return render(request, 'profiles/create-profile.html', context)


def edit_profile(request):
    profile = Profile.objects.first()
    edit_profile_form = EditProfileForm(request.POST or None, instance=profile)

    if request.method == 'POST':
        if edit_profile_form.is_valid():
            edit_profile_form.save()
            return redirect('details_profile',)

    context = {
        'profile': profile,
        'edit_profile_form': edit_profile_form,
    }

    return render(request, 'profiles/edit-profile.html', context)


def details_profile(request):
    profile = Profile.objects.first()

    context = {
        'profile': profile
    }

    return render(request, 'profiles/details-profile.html', context)


def delete_profile(request):
    profile = Profile.objects.first()
    delete_form = DeleteProfileForm(request.POST or None, instance=profile)

    if request.method == 'POST':
        delete_form.save()
        return redirect('main_page')

    context = {
        'profile': profile,
        'delete_form': delete_form,
    }

    return render(request, 'profiles/delete-profile.html', context)

exam_prep_two/templates/profiles/create-profile.html
{% extends 'base.html' %}

{%  block main_content %}

{% load static %}
        <!-- Create Profile Form -->
        <section id="register">
          <div class="form">
            <h2>Create Profile</h2>
            <form class="register-form" action="{% url 'create_profile' %}" method="POST">
                {{ create_form.as_p }}
                {% csrf_token %}
                
{#              <input#}
{#                type="text"#}
{#                name="first-name"#}
{#                id="first-name"#}
{#                placeholder="First Name"#}
{#              />#}
{#              <input#}
{#                type="text"#}
{#                name="last-name"#}
{#                id="last-name"#}
{#                placeholder="Last Name"#}
{#              />#}
{#              <input#}
{#                type="email"#}
{#                name="email"#}
{#                id="register-email"#}
{#                placeholder="Email"#}
{#              />#}
{#              <div class="helptext" id="id_password_helptext">#}
{#                *Password length requirements: 8 to 20 characters#}
{#              </div>#}
{#              <input#}
{#                type="password"#}
{#                name="password"#}
{#                id="register-password"#}
{#                placeholder="Password"#}
{#              />#}

              <button type="submit">Create</button>
            </form>
          </div>
        </section>
{% endblock %}

exam_prep_two/templates/profiles/delete-profile.html
{% extends 'base.html' %}

{%  block main_content %}

{% load static %}

        <section id="edit">

            <div class="form">
                <h1>Are you sure you want to delete your profile?</h1>
                
                <!-- Delete Profile Form -->
                <form id='delete' class="register-form" action="{% url 'delete_profile' %}" method="post">
                    {{ delete_form }}
                    {% csrf_token %}
                    <button type="submit">Yes</button>

                </form>
                <!-- End Delete Profile Form -->
            </div>
            
        </section>

{% endblock %}

exam_prep_two/templates/profiles/details-profile.html
{% extends 'base.html' %}

{%  block main_content %}

{% load static %}

        <!-- Profile Details Section -->

        <section id="details">
            <div id="details-wrapper">
                <h2>Profile Details</h2>
                {% if profile.image_url %}
                <!-- if the user has a profile image -->
                <img id="details-img" src="{{ profile.image_url }}"
                     alt="profile img"/>
                {% else %}
                <!-- if the user has NO profile image -->
                <img id="details-img" src="{% static "images/default.jpg" %}" alt="profile img"/>
                {% endif %}
                <!-- user's full name -->
                <p id="details-title">{{ profile.first_name }} {{ profile.last_name }}</p>

                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- email -->
                        <p>
                            {{ profile.email }}
                        </p>
                        <!-- age -->
                        <p>
                            Age: {{ profile.age }}
                        </p>
                        <!-- number of posts -->
                        <p id="nutrition">Posts: {{ profile.fruits_set.count }}</p>

                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="{% url 'edit_profile' %}" id="edit-btn">Edit</a>
                        <a href="{% url 'delete_profile' %}" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

exam_prep_two/templates/profiles/edit-profile.html
{% extends 'base.html' %}

{%  block main_content %}

{% load static %}
        <!-- Edit Profile Form -->

        <section id="register">
            <div class="form">
                <h2>Edit Profile</h2>
                <form class="register-form" action="{% url 'edit_profile' %}" method="POST">
                    {{ edit_profile_form }}
                    {% csrf_token %}
{#                    <label for="first-name">First Name:</label>#}
{#                    <input#}
{#                            type="text"#}
{#                            name="first name"#}
{#                            id="first-name"#}
{#                            value="Mariya"#}
{#                    />#}
{#                    <label for="last-name">Last Name:</label>#}
{#                    <input#}
{#                            type="text"#}
{#                            name="last name"#}
{#                            id="last-name"#}
{#                            value="Petrova"#}
{#                    />#}
{#                    <label for="url">Image URL:</label>#}
{#                    <input#}
{#                            type="url"#}
{#                            name="url"#}
{#                            id="url"#}
{#                            value="https://images.pexels.com/photos/3792581/pexels-photo-3792581.jpeg"#}
{#                    />#}
{#                    <label for="age">Age:</label>#}
{#                    <input#}
{#                            type="number"#}
{#                            name="age"#}
{#                            id="age"#}
{#                            value="18"#}
{#                    />#}
                    <button type="submit">Edit</button>

                </form>
            </div>
        </section>

{% endblock %}